question_data = [{"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Theodore Roosevelt Jr. was the only General involved in the initial assault on D-Day.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Sir Issac Newton served as a Member of Parliament, but the only recorded time he spoke was to complain about a draft in the chambers.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Franz Joseph I was the last emperor of Austria.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},

                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "The logo for Snapchat is a Bell.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "Time on Computers is measured via the EPOX System.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "The Windows ME operating system was released in the year 2000.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "Linux was first created as an alternative to Windows XP.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},

                 {"category": "Geography",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "The Republic of Malta is the smallest microstate worldwide.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},
                 {"category": "General Knowledge",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Furby was released in 1998.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "Art",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Vincent van Gogh cut off one of his ears.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "Mythology",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "According to Greek Mythology, Zeus can control lightning.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "Science: Gadgets",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "The Western Electric Model 500 telephone uses tone dialing to dial phone numbers.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "hard",
                  "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},

                 {"category": "Celebrities",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Michael Jackson had a pet python named &lsquo;Crusher&rsquo;.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "Entertainment: Music",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "Science: Mathematics",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "The &#039;Squaring the Circle&#039; problem is solvable.",
                  "correct_answer": "False",
                  "incorrect_answers": "True"},
                 {"category": "Entertainment: Video Games",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "Science: Mathematics",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "You can square root a negative number with an imaginary number &quot;i&quot;.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"},
                 {"category": "Sports",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
                  "correct_answer": "True",
                  "incorrect_answers": "False"}
                 ]
